# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-SimpleHTTP
version:      1.13
version_from: lib/POE/Component/Server/SimpleHTTP.pm
installdirs:  site
requires:
    Carp:                          0
    HTTP::Date:                    0
    HTTP::Request:                 0
    HTTP::Response:                0
    POE:                           0.27
    POE::Component::SSLify:        0.04
    Socket:                        0
    Storable:                      0
    Sys::Hostname:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
license: perl
