---
abstract: 'Perl extension to serve HTTP requests in POE.'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  HTTP::Parser: 0.04
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-SimpleHTTP
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Request: 0
  HTTP::Response: 0
  POE: 1.0000
  Socket: 0
  Storable: 0
  Sys::Hostname: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.53_01
