---
abstract: 'Perl extension to serve HTTP requests in POE.'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  POE::Filter::HTTP::Parser: 1.06
  Test::More: 0.47
  Test::POE::Client::TCP: 0.1
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-SimpleHTTP
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Server::SimpleHTTP:
    file: lib/POE/Component/Server/SimpleHTTP.pm
    version: 2.14
  POE::Component::Server::SimpleHTTP::Connection:
    file: lib/POE/Component/Server/SimpleHTTP/Connection.pm
    version: 2.14
  POE::Component::Server::SimpleHTTP::Response:
    file: lib/POE/Component/Server/SimpleHTTP/Response.pm
    version: 2.14
  POE::Component::Server::SimpleHTTP::State:
    file: lib/POE/Component/Server/SimpleHTTP/State.pm
    version: 2.14
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Request: 0
  HTTP::Response: 0
  Moose: 0.81
  MooseX::AttributeHelpers: 0
  MooseX::POE: 0.205
  POE: 1.0000
  Socket: 0
  Storable: 0
  Sys::Hostname: 0
  perl: 5.6.0
resources:
  homepage: https://github.com/bingos/poe-component-server-simplehttp/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/bingos/poe-component-server-simplehttp.git
    web: https://github.com/bingos/poe-component-server-simplehttp/tree
version: 2.14
