---
abstract: 'Perl extension to serve HTTP requests in POE.'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  POE::Filter::HTTP::Parser: 0.02
  Test::More: 0.47
  Test::POE::Client::TCP: 0.1
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-SimpleHTTP
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Request: 0
  HTTP::Response: 0
  POE: 1.0000
  Socket: 0
  Storable: 0
  Sys::Hostname: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.56
