---
abstract: 'Perl extension to serve HTTP requests in POE.'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
build_requires:
  LWP::ConnCache: 0
  LWP::UserAgent: 0
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Server-SimpleHTTP
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Request: 0
  HTTP::Response: 0
  POE: 1.0000
  Socket: 0
  Storable: 0
  Sys::Hostname: 0
version: 1.46
